import assert from 'node:assert/strict'
import { execFile } from 'node:child_process'
import { existsSync, renameSync, rmSync } from 'node:fs'
import path from 'node:path'
import { promisify } from 'node:util'
import pg from 'pg'

import { bootstrapDatabase } from '../scripts/staging/database'

// The Staging database bootstrap (scripts/staging-prepare.ts via bootstrapDatabase): self-contained Prisma generate →
// migrate deploy → QA accounts, with stage-specific, redacted failures. Requires STAGING_OPERATOR_TEST_ADMIN_URL
// (superuser URL of a disposable local PostgreSQL).

const adminUrl = process.env.STAGING_OPERATOR_TEST_ADMIN_URL
if (!adminUrl) { console.error('STAGING_OPERATOR_TEST_ADMIN_URL is required (disposable local PostgreSQL)'); process.exit(1) }
const local = new URL(adminUrl)
const SECRET = 'secret-pw-7f3a9c'
const url = `postgresql://${local.username}:${SECRET}@${local.hostname}:${local.port || 5432}/op_prepare_test`
const client = path.join(process.cwd(), 'node_modules', '.prisma')
const stale = `${client}.stale-test`

async function prepare(hostnames: string) {
  try {
    const { stdout, stderr } = await promisify(execFile)(process.execPath, [path.join('node_modules', 'tsx', 'dist', 'cli.mjs'), 'scripts/staging-prepare.ts'], { env: { PATH: process.env.PATH!, HOME: process.env.HOME!, GERARD_INSTANCE_ENVIRONMENT: 'staging', DATABASE_URL: url, GERARD_PLATFORM_HOSTNAMES: hostnames, GERARD_STAGING_SUPERADMIN_INITIAL_PASSWORD: 'Initial-Password-For-Test-1' } as unknown as NodeJS.ProcessEnv, maxBuffer: 32 * 1024 * 1024 })
    return { code: 0, output: stdout + stderr }
  } catch (error: any) {
    return { code: error.code ?? 1, output: `${error.stdout ?? ''}${error.stderr ?? ''}` }
  }
}
const noSecret = (output: string, label: string) => { assert.ok(!output.includes(SECRET) && !/postgres(ql)?:\/\//.test(output), `${label}: no password or database URL in the output`) }

async function main() {
  const admin = new pg.Client({ connectionString: adminUrl }); await admin.connect()
  await admin.query('drop database if exists op_prepare_test with (force)'); await admin.query('create database op_prepare_test'); await admin.end()

  // 1–3. No generated Prisma Client on the machine: prepare generates it, then migrates, then bootstraps the QA account.
  if (existsSync(stale)) rmSync(stale, { recursive: true, force: true })
  renameSync(client, stale)
  let first
  try {
    first = await prepare('gerard-staging.vercel.app')
  } finally {
    if (!existsSync(path.join(client, 'client'))) { rmSync(client, { recursive: true, force: true }); renameSync(stale, client) } else rmSync(stale, { recursive: true, force: true })
  }
  assert.equal(first.code, 0, first.output)
  assert.ok(existsSync(path.join(client, 'client', 'index.js')), 'Prisma Client generated by prepare itself')
  const order = ['staging-prepare: prisma generate', 'staging-prepare: prisma migrate deploy', 'staging-prepare: QA accounts', 'staging-prepare: gerard.staging.superadmin created'].map((marker) => first.output.indexOf(marker))
  assert.ok(order.every((index) => index >= 0) && order.every((index, position) => position === 0 || index > order[position - 1]), `generate → migrate → QA order (${order.join(', ')})`)
  noSecret(first.output, 'successful prepare')

  // 4. A real QA failure (Staging hostname already mapped to another organization) surfaces its stage and cause.
  const db = new pg.Client({ connectionString: url }); await db.connect()
  await db.query(`insert into "Organization" (id, name, slug, "updatedAt") values ('org-other', 'Other', 'other', now())`)
  await db.query(`insert into "OrganizationDomain" (id, "organizationId", hostname, "updatedAt") values ('od-taken', 'org-other', 'taken.example', now())`)
  await db.query(`comment on schema public is 'gerard-staging-sanitized:{"branch":"br-test","parent":"br-parent","app":"gerard","at":"now"}'`)
  await db.end()
  const failed = await prepare('taken.example')
  assert.notEqual(failed.code, 0)
  assert.match(failed.output, /staging-prepare failed: STAGING_QA_BOOTSTRAP_FAILED: STAGING_HOSTNAME_MAPPED_ELSEWHERE:taken\.example/)
  noSecret(failed.output, 'failed prepare')

  // …and reaches the operator through bootstrapDatabase (setup prints it) instead of a generic message.
  const result = await bootstrapDatabase({ url, app: 'gerard', branch: { id: 'br-test', name: 'test', parent_id: 'br-parent' }, hosts: ['taken.example'], initialPassword: 'Initial-Password-For-Test-1' })
  assert.equal(result.prepared, false)
  assert.match(result.problems[0], /^STAGING_QA_BOOTSTRAP_FAILED\n[\s\S]*STAGING_HOSTNAME_MAPPED_ELSEWHERE:taken\.example/)
  assert.match(result.problems[0], /staging-prepare: prisma migrate deploy/, 'earlier stages visible in the surfaced output')
  noSecret(result.problems.join('\n') + result.log, 'surfaced bootstrap failure')

  const cleanup = new pg.Client({ connectionString: adminUrl }); await cleanup.connect(); await cleanup.query('drop database if exists op_prepare_test with (force)'); await cleanup.end()
  console.log('Staging prepare: self-contained generate → migrate → QA, stage-specific redacted failures: OK')
}

main().catch((error) => { console.error(error); process.exitCode = 1 })
