import { existsSync } from 'node:fs'
import { tmpdir } from 'node:os'
import path from 'node:path'

import { APPS, LABEL, SCOPE, STAGING_PROJECTS, VERCEL_CLI, assertStagingProject, fail, flags, log, main, resolveProjects, run, runCli, stableHost, vercelCli, type App } from './lib'

// npm run staging:deploy               → gerard-staging + novotralux-custom-staging
// npm run gerard:staging:deploy        → gerard-staging only
// npm run novotralux:staging:deploy    → novotralux-custom-staging only
// Deploys the current Git commit (HEAD) from a clean temporary worktree: local files that are not committed (.env,
// generated files, build output) never reach Staging. Only the two Staging projects can be targeted; the repository's
// own .vercel link, if any, is neither read nor changed.

// Generated by `next dev` / TypeScript; never meaningful source changes.
const GENERATED = new Set(['next-env.d.ts', 'tsconfig.tsbuildinfo', 'apps/novotralux/tsconfig.tsbuildinfo', 'packages/gerard-core/tsconfig.tsbuildinfo'])

// Meaningful changes in `git status --porcelain` output: everything except generated files.
export const meaningfulChanges = (porcelain: string) => porcelain.split('\n').map((line) => line.slice(3).trim().replace(/^"|"$/g, '')).filter((file) => file && !GENERATED.has(file.replace(/\\/g, '/')))

export async function deployToStaging(apps: App[], options: { allowDirty?: boolean } = {}) {
  const changes = meaningfulChanges((await run('git', ['status', '--porcelain'], { quiet: true })).stdout)
  if (changes.length && options.allowDirty) log(`⚠ Uncommitted changes are NOT deployed (${changes.length} file(s)); deploying commit HEAD only.`)
  else if (changes.length) fail(`Uncommitted changes (${changes.slice(0, 5).join(', ')}${changes.length > 5 ? ', …' : ''}): commit or stash them; Staging deploys the current commit only.`)
  const branch = (await run('git', ['rev-parse', '--abbrev-ref', 'HEAD'], { quiet: true })).stdout.trim()
  const commit = (await run('git', ['rev-parse', 'HEAD'], { quiet: true })).stdout.trim()
  const { staging } = await resolveProjects()
  const targets = apps.map((app) => {
    const project = staging[app] ?? fail(`${STAGING_PROJECTS[app]} does not exist yet: run npm run staging:setup first.`)
    return { app, name: assertStagingProject(STAGING_PROJECTS[app]), id: project.id }
  })
  const worktree = path.join(tmpdir(), `gerard-staging-${commit.slice(0, 12)}-${Date.now()}`)
  if ((await run('git', ['worktree', 'add', '--detach', worktree, commit], { quiet: true })).code !== 0) fail('Could not create the temporary deployment worktree.')
  try {
    for (const target of targets) {
      // The team id comes from Vercel for the Staging project itself; the id must match the resolved Staging project.
      const remote = await vercelCli.api(`/v9/projects/${target.name}`) as { id: string; name: string; accountId: string }
      if (remote.id !== target.id || remote.name !== target.name) fail(`${target.name}: project identity mismatch: refused.`)
      log(`\n→ ${branch}@${commit.slice(0, 7)} → ${LABEL[target.app]} (${target.name})`)
      const result = await runCli(VERCEL_CLI, ['deploy', '--prod', '--yes', '--scope', SCOPE], { cwd: worktree, env: { VERCEL_ORG_ID: remote.accountId, VERCEL_PROJECT_ID: remote.id } })
      if (result.code !== 0) fail(`${target.name}: deployment failed (see the Vercel output above).`)
      log(`✔ ${LABEL[target.app]}: https://${(await stableHost(target.name)) ?? `${target.name}.vercel.app`}`)
    }
  } finally {
    await run('git', ['worktree', 'remove', '--force', worktree], { quiet: true })
    if (existsSync(worktree)) log(`(temporary worktree left at ${worktree}; remove it with git worktree prune)`)
  }
}

if (/deploy\.ts$/.test(process.argv[1] ?? '')) {
  main(async () => {
    const { positional, has } = flags()
    const requested = positional.length ? positional : APPS
    if (!requested.every((item) => (APPS as string[]).includes(item))) fail(`Unknown application: use ${APPS.join(' | ')}`)
    // Novotralux first: Gerard Staging's channel targets it.
    await deployToStaging(APPS.filter((app) => requested.includes(app)).reverse(), { allowDirty: has('--allow-dirty') })
    log('\nNext: npm run staging:check')
  })
}
