ALTER TYPE "PlatformAuditAction" ADD VALUE IF NOT EXISTS 'MEMBER_STATUS_CHANGED';
ALTER TYPE "PlatformAuditAction" ADD VALUE IF NOT EXISTS 'PASSWORD_RESET';
ALTER TYPE "PlatformAuditAction" ADD VALUE IF NOT EXISTS 'SESSION_INVALIDATED';
