import type { GetServerSideProps } from 'next'
import { FormEvent, useEffect, useMemo, useState } from 'react'
import { LogoutButton } from '../../components/site/LogoutButton'
import { getCurrentUser } from '../../lib/auth/authorization'

const roles = ['ORG_ADMIN', 'MANAGER', 'DISPATCHER', 'SECRETARY', 'ACCOUNTING', 'DRIVER', 'VIEWER'] as const
const roleDescriptions: Record<string, string> = { ORG_ADMIN: 'Administration et accès', MANAGER: 'Gestion opérationnelle', DISPATCHER: 'Planification et dispatch', SECRETARY: 'Flux administratifs', ACCOUNTING: 'Facturation et finances', DRIVER: 'Espace conducteur', VIEWER: 'Consultation uniquement' }
const sections = ['overview', 'members', 'access', 'security', 'modules', 'integrations', 'appearance', 'activity', 'settings'] as const
const labels: Record<string, string> = { overview: 'Vue d’ensemble', members: 'Membres', access: 'Accès & rôles', security: 'Sécurité', modules: 'Modules', integrations: 'Intégrations', appearance: 'Apparence', activity: 'Activité', settings: 'Paramètres' }
const moduleDescriptions: Record<string, string> = { PLANNING: 'Planning et affectations', MAP: 'Carte et suivi', PROFITABILITY: 'Rentabilité', INVOICING: 'Facturation', FLEET: 'Flotte et parc', MAINTENANCE: 'Maintenance', INTELLIGENCE: 'Gerard Intelligence', ASSISTANT: 'Assistant opérationnel' }
type Member = { id: string; role: string; createdAt: string; user: { id: string; firstName: string; lastName: string; username: string; email: string | null; isActive: boolean; mustChangePassword: boolean; lastLoginAt: string | null; createdAt: string; sessionVersion: number } }
type Integration = { id: string; type: string; enabled: boolean; configJson: Record<string, unknown>; updatedAt: string }
type Activity = { id: string; action: string; metadata: Record<string, unknown> | null; createdAt: string; actor: { firstName: string; lastName: string; username: string } }
type MemberForm = { firstName: string; lastName: string; username: string; email: string; role: string }
type Organization = { id: string; name: string; slug: string; status: string; enabledModules: string[]; displayName: string | null; applicationTitle: string | null; accentColor: string | null; logoUrl: string | null; faviconUrl: string | null; users: Member[]; integrations: Integration[]; platformAuditLogs: Activity[] }

const formatDate = (value: string | null) => value ? new Intl.DateTimeFormat('fr-BE', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : 'Jamais'
const badge = (tone: 'green' | 'amber' | 'gray' | 'red') => `inline-flex rounded-full px-2.5 py-1 text-[11px] font-black uppercase tracking-wide ${tone === 'green' ? 'bg-lime-100 text-lime-900' : tone === 'amber' ? 'bg-amber-100 text-amber-900' : tone === 'red' ? 'bg-red-100 text-red-800' : 'bg-black/5 text-black/55'}`

export default function OrganizationAdminPage({ accessDenied = false, platformAdmin = false }: { accessDenied?: boolean; platformAdmin?: boolean }) {
  const [organization, setOrganization] = useState<Organization | null>(null)
  const [section, setSection] = useState<(typeof sections)[number]>('overview')
  const [selected, setSelected] = useState<Member | null>(null)
  const [search, setSearch] = useState(''); const [roleFilter, setRoleFilter] = useState('ALL'); const [statusFilter, setStatusFilter] = useState('ALL'); const [sortBy, setSortBy] = useState('NAME')
  const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [temporaryPassword, setTemporaryPassword] = useState('')
  const [form, setForm] = useState({ firstName: '', lastName: '', username: '', email: '', role: 'VIEWER' })
  const load = async () => { const response = await fetch('/api/admin/organization'); const body = await response.json(); if (!response.ok) throw new Error(body.error || 'Chargement impossible'); setOrganization(body.organization); setSelected((current) => current ? body.organization.users.find((item: Member) => item.id === current.id) || null : null) }
  useEffect(() => { if (!accessDenied) void load().catch((cause) => setError(cause.message)) }, [accessDenied])
  const request = async (url: string, init: RequestInit) => { setError(''); setNotice(''); const response = await fetch(url, { ...init, headers: { 'Content-Type': 'application/json' } }); const body = await response.json(); if (!response.ok) throw new Error(body.error || 'Opération impossible'); await load(); return body }
  const filtered = useMemo(() => (organization?.users || []).filter(({ role, user }) => `${user.firstName} ${user.lastName} ${user.username} ${user.email || ''}`.toLowerCase().includes(search.toLowerCase()) && (roleFilter === 'ALL' || role === roleFilter) && (statusFilter === 'ALL' || (statusFilter === 'ACTIVE' ? user.isActive : !user.isActive))).sort((a, b) => sortBy === 'ROLE' ? a.role.localeCompare(b.role) : sortBy === 'LAST_LOGIN' ? (b.user.lastLoginAt || '').localeCompare(a.user.lastLoginAt || '') : `${a.user.lastName} ${a.user.firstName}`.localeCompare(`${b.user.lastName} ${b.user.firstName}`)), [organization, search, roleFilter, statusFilter, sortBy])
  const stats = useMemo(() => ({ total: organization?.users.length || 0, active: organization?.users.filter((m) => m.user.isActive).length || 0, disabled: organization?.users.filter((m) => !m.user.isActive).length || 0, admins: organization?.users.filter((m) => m.role === 'ORG_ADMIN' && m.user.isActive).length || 0 }), [organization])
  const addMember = async (event: FormEvent) => { event.preventDefault(); try { const body = await request('/api/admin/organization/members', { method: 'POST', body: JSON.stringify(form) }); setTemporaryPassword(body.temporaryPassword); setNotice('Membre créé. Ce mot de passe ne sera plus affiché.'); setForm({ firstName: '', lastName: '', username: '', email: '', role: 'VIEWER' }) } catch (cause) { setError(cause instanceof Error ? cause.message : 'Création impossible') } }
  const saveSettings = async (event: FormEvent) => { event.preventDefault(); if (!organization) return; try { await request('/api/admin/organization', { method: 'PATCH', body: JSON.stringify({ name: organization.name, displayName: organization.displayName, applicationTitle: organization.applicationTitle, accentColor: organization.accentColor, logoUrl: organization.logoUrl, faviconUrl: organization.faviconUrl }) }); setNotice('Paramètres enregistrés.') } catch (cause) { setError(cause instanceof Error ? cause.message : 'Enregistrement impossible') } }
  const memberAction = async (action: 'reset' | 'sessions' | 'status', member: Member) => { if (!confirm(action === 'reset' ? `Réinitialiser le mot de passe de ${member.user.username} ?` : action === 'sessions' ? `Déconnecter ${member.user.username} de tous les appareils ?` : `${member.user.isActive ? 'Désactiver' : 'Réactiver'} ce compte ?`)) return; try { const body = action === 'reset' ? await request(`/api/admin/organization/members/${member.id}/reset-password`, { method: 'POST' }) : action === 'sessions' ? await request(`/api/admin/organization/members/${member.id}/invalidate-sessions`, { method: 'POST' }) : await request(`/api/admin/organization/members/${member.id}`, { method: 'PATCH', body: JSON.stringify({ isActive: !member.user.isActive }) }); if (body.temporaryPassword) setTemporaryPassword(body.temporaryPassword); setNotice(action === 'reset' ? 'Mot de passe temporaire généré. Ce mot de passe ne sera plus affiché.' : action === 'sessions' ? 'Toutes les sessions ont été invalidées.' : 'Statut du membre mis à jour.') } catch (cause) { setError(cause instanceof Error ? cause.message : 'Action impossible') } }
  if (accessDenied) return <main className="flex min-h-screen items-center justify-center bg-[#eef0ea] p-6"><section className="max-w-lg rounded-3xl bg-[#11130f] p-8 text-white"><h1 className="text-3xl font-semibold">Accès interdit</h1><p className="mt-3 text-white/60">Cette zone est réservée aux ORG_ADMIN de l’organisation active.</p><a className="mt-6 inline-flex rounded-xl bg-white px-4 py-3 font-bold text-black" href="/dispatch">Retour au dispatch</a></section></main>
  if (!organization) return <main className="min-h-screen bg-[#eef0ea] p-8"><div className="mx-auto h-64 max-w-6xl animate-pulse rounded-[30px] bg-black/10" /></main>
  return <main className="min-h-screen bg-[#eef0ea] text-[#171914]"><div className="mx-auto max-w-[1440px] px-4 py-5 lg:px-7">
    <header className="rounded-[28px] bg-[#11130f] px-6 py-6 text-white"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.25em] text-[#C8FF00]">Organisation · {organization.status}</p><h1 className="mt-2 text-3xl font-semibold">{organization.displayName || organization.name}</h1><p className="mt-1 text-sm text-white/50">Administration autonome de votre espace Gerard</p></div><div className="flex gap-2"><a href="/dispatch" className="rounded-xl bg-white/10 px-4 py-3 text-sm font-bold">Dispatch</a>{platformAdmin && <a href="/admin" className="rounded-xl bg-[#C8FF00] px-4 py-3 text-sm font-bold text-black">Plateforme</a>}<LogoutButton tone="dark" /></div></div></header>
    {error && <div className="mt-3 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm font-bold text-red-900">{error}</div>}{notice && <div className="mt-3 rounded-2xl border border-lime-200 bg-lime-50 p-4 text-sm font-bold text-lime-950">{notice}</div>}
    {temporaryPassword && <div className="mt-3 rounded-2xl border border-amber-300 bg-amber-50 p-4"><p className="font-bold">Mot de passe temporaire</p><p className="text-sm text-amber-900">Ce mot de passe ne sera plus affiché.</p><div className="mt-3 flex gap-2"><code className="flex-1 break-all rounded-xl bg-white p-3">{temporaryPassword}</code><button onClick={() => void navigator.clipboard.writeText(temporaryPassword)} className="rounded-xl bg-black px-4 text-sm font-bold text-white">Copier</button><button onClick={() => setTemporaryPassword('')} className="rounded-xl border px-4 text-sm font-bold">Fermer</button></div></div>}
    <div className="mt-5 grid gap-5 lg:grid-cols-[220px_1fr]"><nav className="flex gap-2 overflow-auto rounded-2xl bg-white p-2 lg:sticky lg:top-4 lg:block lg:h-fit lg:space-y-1">{sections.map((item) => <button key={item} onClick={() => setSection(item)} className={`whitespace-nowrap rounded-xl px-4 py-3 text-left text-sm font-bold lg:w-full ${section === item ? 'bg-[#11130f] text-[#C8FF00]' : 'text-black/55 hover:bg-black/5'}`}>{labels[item]}</button>)}</nav>
      <section className="min-w-0">
        {section === 'overview' && <div className="space-y-5"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[['Membres', stats.total], ['Actifs', stats.active], ['Désactivés', stats.disabled], ['Administrateurs', stats.admins]].map(([label, value]) => <article key={label} className="rounded-2xl bg-white p-5"><p className="text-xs font-black uppercase tracking-wider text-black/40">{label}</p><p className="mt-2 text-3xl font-semibold">{value}</p></article>)}</div><article className="rounded-3xl bg-white p-6"><h2 className="text-xl font-semibold">Actions rapides</h2><div className="mt-4 flex flex-wrap gap-2">{[['members', 'Ajouter un membre'], ['access', 'Gérer les rôles'], ['appearance', 'Personnaliser'], ['security', 'Sécurité'], ['integrations', 'Voir les intégrations']].map(([target, label]) => <button key={target} onClick={() => setSection(target as typeof section)} className="rounded-xl border px-4 py-3 text-sm font-bold hover:bg-[#C8FF00]">{label}</button>)}</div></article><article className="grid gap-4 rounded-3xl bg-white p-6 md:grid-cols-2"><div><h2 className="text-lg font-semibold">Modules actifs</h2><p className="mt-2 text-sm text-black/50">{organization.enabledModules.length} module(s) · {organization.enabledModules.join(', ')}</p></div><div><h2 className="text-lg font-semibold">Santé des intégrations</h2><p className="mt-2 text-sm text-black/50">{organization.integrations.filter((item) => item.enabled).length} active(s) sur {organization.integrations.length}</p></div></article><article className="rounded-3xl bg-white p-6"><h2 className="text-xl font-semibold">Activité récente</h2><ActivityList items={organization.platformAuditLogs.slice(0, 6)} compact /></article></div>}
        {section === 'members' && <div className="space-y-5"><article className="rounded-3xl bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-2xl font-semibold">Membres</h2><p className="text-sm text-black/45">{filtered.length} résultat(s)</p></div><button onClick={() => document.getElementById('new-member')?.scrollIntoView({ behavior: 'smooth' })} className="rounded-xl bg-[#C8FF00] px-4 py-3 text-sm font-black">＋ Ajouter</button></div><div className="mt-4 grid gap-2 md:grid-cols-4"><input className="rounded-xl border p-3" placeholder="Rechercher un membre…" value={search} onChange={(e) => setSearch(e.target.value)} /><select className="rounded-xl border p-3" value={roleFilter} onChange={(e) => setRoleFilter(e.target.value)}><option value="ALL">Tous les rôles</option>{roles.map((r) => <option key={r}>{r}</option>)}</select><select className="rounded-xl border p-3" value={statusFilter} onChange={(e) => setStatusFilter(e.target.value)}><option value="ALL">Tous les statuts</option><option value="ACTIVE">Actifs</option><option value="DISABLED">Désactivés</option></select><select className="rounded-xl border p-3" value={sortBy} onChange={(e) => setSortBy(e.target.value)}><option value="NAME">Trier par nom</option><option value="ROLE">Trier par rôle</option><option value="LAST_LOGIN">Dernière connexion</option></select></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[820px] text-left text-sm"><thead className="border-b text-xs uppercase text-black/40"><tr><th className="p-3">Utilisateur</th><th className="p-3">Identifiant</th><th className="p-3">Rôle</th><th className="p-3">Statut</th><th className="p-3">Dernière connexion</th><th className="p-3">Mot de passe</th><th /></tr></thead><tbody>{filtered.map((m) => <tr key={m.id} className="border-b border-black/5"><td className="p-3 font-bold">{m.user.firstName} {m.user.lastName}</td><td className="p-3 text-black/55">{m.user.email || m.user.username}</td><td className="p-3">{m.role}</td><td className="p-3"><span className={badge(m.user.isActive ? 'green' : 'gray')}>{m.user.isActive ? 'ACTIVE' : 'DISABLED'}</span></td><td className="p-3 text-black/55">{formatDate(m.user.lastLoginAt)}</td><td className="p-3">{m.user.mustChangePassword ? <span className={badge('amber')}>À changer</span> : <span className={badge('green')}>À jour</span>}</td><td className="p-3 text-right"><button onClick={() => setSelected(m)} className="rounded-lg border px-3 py-2 font-bold">Gérer</button></td></tr>)}</tbody></table></div></article><NewMemberForm form={form} setForm={setForm} onSubmit={addMember} /></div>}
        {section === 'access' && <Panel title="Accès & rôles" subtitle="Les rôles disponibles correspondent aux permissions réellement prises en charge."><div className="grid gap-3 md:grid-cols-2">{roles.map((role) => <div key={role} className="rounded-2xl border p-4"><p className="font-black">{role}</p><p className="mt-1 text-sm text-black/50">{roleDescriptions[role]}</p></div>)}</div></Panel>}
        {section === 'security' && <Panel title="Sécurité" subtitle="Contrôlez les mots de passe et sessions depuis la fiche de chaque membre."><div className="grid gap-3 md:grid-cols-3"><SecurityCard title="Sessions" text="Déconnectez un utilisateur de tous ses appareils en incrémentant sa version de session." /><SecurityCard title="Mots de passe" text="Les mots de passe temporaires sont chiffrés et affichés une seule fois." /><SecurityCard title="Protection" text="Le dernier ORG_ADMIN et les comptes plateforme ne peuvent pas être désactivés ici." /></div></Panel>}
        {section === 'modules' && <Panel title="Modules" subtitle="Les modules sont gérés par la plateforme."><div className="grid gap-3 md:grid-cols-2">{Object.entries(moduleDescriptions).map(([module, description]) => { const active = organization.enabledModules.includes(module); return <div key={module} className="flex items-center justify-between rounded-2xl border p-4"><div><p className="font-black">{module}</p><p className="text-sm text-black/45">{description}</p></div><span className={badge(active ? 'green' : 'gray')}>{active ? 'ACTIVE' : 'DISABLED'}</span></div> })}</div></Panel>}
        {section === 'integrations' && <Panel title="Intégrations" subtitle="État opérationnel et métadonnées non sensibles."><div className="grid gap-3 md:grid-cols-2">{organization.integrations.map((integration) => <div key={integration.id} className="rounded-2xl border p-5"><div className="flex justify-between gap-3"><h3 className="font-black">{integration.type}</h3><span className={badge(integration.enabled ? 'green' : 'gray')}>{integration.enabled ? 'CONNECTED' : 'DISABLED'}</span></div><p className="mt-3 text-sm text-black/55">{integration.type === 'MAIL_INTAKE' ? String(integration.configJson.mailboxAddress || integration.configJson.provider || 'Configuration masquée') : String(integration.configJson.providerName || 'Fournisseur configuré')}</p><p className="mt-2 text-xs text-black/35">Mis à jour {formatDate(integration.updatedAt)}</p></div>)}</div>{!organization.integrations.length && <p className="rounded-2xl bg-black/5 p-5 text-sm text-black/50">Aucune intégration configurée.</p>}</Panel>}
        {section === 'appearance' && <Panel title="Apparence" subtitle="Prévisualisez l’identité visuelle de votre organisation."><div className="grid gap-5 lg:grid-cols-2"><SettingsForm organization={organization} setOrganization={setOrganization} onSubmit={saveSettings} appearanceOnly /><div className="rounded-3xl p-6 text-white" style={{ background: organization.accentColor || '#11130f' }}><p className="text-xs font-black uppercase tracking-widest opacity-60">Aperçu</p><h3 className="mt-12 text-3xl font-semibold">{organization.applicationTitle || organization.displayName || organization.name}</h3><p className="mt-2 opacity-70">Votre espace opérationnel Gerard</p></div></div></Panel>}
        {section === 'activity' && <Panel title="Activité" subtitle="Événements administratifs récents, sans données sensibles."><ActivityList items={organization.platformAuditLogs} /></Panel>}
        {section === 'settings' && <Panel title="Paramètres" subtitle={`Identifiant stable : /${organization.slug}`}><SettingsForm organization={organization} setOrganization={setOrganization} onSubmit={saveSettings} /></Panel>}
      </section></div>
    {selected && <MemberDrawer member={selected} close={() => setSelected(null)} request={request} action={memberAction} />}
  </div></main>
}

function Panel({ title, subtitle, children }: { title: string; subtitle: string; children: React.ReactNode }) { return <article className="rounded-3xl bg-white p-6"><h2 className="text-2xl font-semibold">{title}</h2><p className="mt-1 text-sm text-black/45">{subtitle}</p><div className="mt-6">{children}</div></article> }
function SecurityCard({ title, text }: { title: string; text: string }) { return <div className="rounded-2xl border p-5"><p className="font-black">{title}</p><p className="mt-2 text-sm leading-6 text-black/50">{text}</p></div> }
function ActivityList({ items, compact = false }: { items: Activity[]; compact?: boolean }) { const [actor, setActor] = useState('ALL'); const [action, setAction] = useState('ALL'); const [date, setDate] = useState(''); const actors = Array.from(new Set(items.map((item) => item.actor.username))); const actions = Array.from(new Set(items.map((item) => item.action))); const visible = items.filter((item) => (actor === 'ALL' || item.actor.username === actor) && (action === 'ALL' || item.action === action) && (!date || item.createdAt.startsWith(date))); return <div className="mt-4">{!compact && <div className="grid gap-2 md:grid-cols-3"><select className="rounded-xl border p-3" value={actor} onChange={(e) => setActor(e.target.value)}><option value="ALL">Tous les acteurs</option>{actors.map((value) => <option key={value}>{value}</option>)}</select><select className="rounded-xl border p-3" value={action} onChange={(e) => setAction(e.target.value)}><option value="ALL">Toutes les actions</option>{actions.map((value) => <option key={value}>{value}</option>)}</select><input className="rounded-xl border p-3" type="date" value={date} onChange={(e) => setDate(e.target.value)} /></div>}<div className="mt-3 divide-y">{visible.map((item) => <div key={item.id} className="grid gap-1 py-3 text-sm md:grid-cols-[180px_1fr_180px]"><span className="text-black/40">{formatDate(item.createdAt)}</span><span className="font-bold">{item.action.replaceAll('_', ' ')}</span><span className="text-black/45">{item.actor.firstName} {item.actor.lastName || item.actor.username}</span></div>)}{!visible.length && <p className="py-8 text-center text-sm text-black/40">Aucune activité récente.</p>}</div></div> }
function NewMemberForm({ form, setForm, onSubmit }: { form: MemberForm; setForm: (value: MemberForm) => void; onSubmit: (event: FormEvent) => void }) { return <form id="new-member" onSubmit={onSubmit} className="grid gap-3 rounded-3xl bg-white p-6 sm:grid-cols-2"><div className="sm:col-span-2"><h3 className="text-xl font-semibold">Ajouter un membre</h3><p className="text-sm text-black/45">Un mot de passe temporaire sécurisé sera généré.</p></div>{(['firstName', 'lastName', 'username', 'email'] as const).map((field) => <input key={field} required={field !== 'email'} value={form[field]} onChange={(e) => setForm({ ...form, [field]: e.target.value })} placeholder={{ firstName: 'Prénom', lastName: 'Nom', username: 'Nom d’utilisateur', email: 'Email (optionnel)' }[field]} className="rounded-xl border p-3" />)}<select value={form.role} onChange={(e) => setForm({ ...form, role: e.target.value })} className="rounded-xl border p-3">{roles.map((role) => <option key={role}>{role}</option>)}</select><button className="rounded-xl bg-black p-3 font-bold text-white">Créer le membre</button></form> }
function SettingsForm({ organization, setOrganization, onSubmit, appearanceOnly = false }: { organization: Organization; setOrganization: (value: Organization) => void; onSubmit: (event: FormEvent) => void; appearanceOnly?: boolean }) { const fields = appearanceOnly ? [['displayName', 'Nom affiché'], ['applicationTitle', 'Titre de l’application'], ['accentColor', 'Couleur accent'], ['logoUrl', 'URL du logo'], ['faviconUrl', 'URL du favicon']] : [['name', 'Nom légal/interne'], ['displayName', 'Nom affiché'], ['applicationTitle', 'Titre de l’application']]; return <form onSubmit={onSubmit} className="space-y-3">{fields.map(([field, label]) => <label key={field} className="block text-xs font-black">{label}<input value={String(organization[field as keyof Organization] || '')} onChange={(e) => setOrganization({ ...organization, [field]: e.target.value || null })} className="mt-1 w-full rounded-xl border p-3 text-sm font-normal" /></label>)}<button className="rounded-xl bg-black px-5 py-3 text-sm font-bold text-white">Enregistrer</button></form> }
function MemberDrawer({ member, close, request, action }: { member: Member; close: () => void; request: (url: string, init: RequestInit) => Promise<unknown>; action: (action: 'reset' | 'sessions' | 'status', member: Member) => Promise<void> }) { return <div className="fixed inset-0 z-50 flex justify-end bg-black/40" onClick={close}><aside className="h-full w-full max-w-lg overflow-y-auto bg-[#f7f8f5] p-6 shadow-2xl" onClick={(e) => e.stopPropagation()}><div className="flex justify-between"><div><p className="text-xs font-black uppercase tracking-widest text-black/40">Membre</p><h2 className="mt-1 text-2xl font-semibold">{member.user.firstName} {member.user.lastName}</h2><p className="text-sm text-black/45">@{member.user.username}</p></div><button onClick={close} className="h-10 w-10 rounded-full border text-xl">×</button></div><div className="mt-6 space-y-4"><Panel title="Identité" subtitle={member.user.email || 'Aucun email'}><p className="text-sm">Créé le {formatDate(member.user.createdAt)}</p></Panel><Panel title="Accès" subtitle={roleDescriptions[member.role] || ''}><select value={member.role} onChange={(e) => void request(`/api/admin/organization/members/${member.id}`, { method: 'PATCH', body: JSON.stringify({ role: e.target.value }) })} className="w-full rounded-xl border p-3">{roles.map((role) => <option key={role}>{role}</option>)}</select><button onClick={() => void action('status', member)} className={`mt-3 w-full rounded-xl px-4 py-3 font-bold ${member.user.isActive ? 'bg-red-100 text-red-900' : 'bg-lime-100 text-lime-900'}`}>{member.user.isActive ? 'Désactiver le compte' : 'Réactiver le compte'}</button></Panel><Panel title="Sécurité" subtitle={`Dernière connexion : ${formatDate(member.user.lastLoginAt)}`}><p className="text-sm">Mot de passe : {member.user.mustChangePassword ? 'changement requis' : 'à jour'}</p><div className="mt-4 grid gap-2"><button onClick={() => void action('reset', member)} className="rounded-xl bg-black px-4 py-3 font-bold text-white">Réinitialiser le mot de passe</button><button onClick={() => void action('sessions', member)} className="rounded-xl border px-4 py-3 font-bold">Déconnecter de tous les appareils</button></div></Panel></div></aside></div> }

export const getServerSideProps: GetServerSideProps = async ({ req, res }) => { const user = await getCurrentUser(req); if (!user || user.organizationRole !== 'ORG_ADMIN' || !user.isActive || user.mustChangePassword) { res.statusCode = 403; return { props: { accessDenied: true } } }; return { props: { platformAdmin: Boolean(user.platformRole) } } }
