import type { GetServerSideProps } from 'next'
import { FormEvent, ReactNode, useEffect, useMemo, useState } from 'react'

import { getPlatformUser } from '../lib/auth/platform-authorization'
import { LogoutButton } from '../components/site/LogoutButton'

const modules = ['PLANNING', 'MAP', 'PROFITABILITY', 'INVOICING', 'FLEET', 'INTELLIGENCE', 'ASSISTANT', 'MAINTENANCE'] as const
const roles = ['ORG_ADMIN', 'MANAGER', 'DISPATCHER', 'SECRETARY', 'ACCOUNTING', 'DRIVER', 'VIEWER'] as const
const moduleLabels: Record<string, string> = { PLANNING: 'Planning', MAP: 'Carte', PROFITABILITY: 'Rentabilité', INVOICING: 'Facturation', FLEET: 'Parc', INTELLIGENCE: 'Intelligence', ASSISTANT: 'Assistant', MAINTENANCE: 'Maintenance' }
const roleLabels: Record<string, string> = { ORG_ADMIN: 'Admin organisation', MANAGER: 'Manager', DISPATCHER: 'Dispatcher', SECRETARY: 'Secrétariat', ACCOUNTING: 'Comptabilité', DRIVER: 'Chauffeur', VIEWER: 'Lecture seule' }
const statusLabels: Record<string, string> = { ACTIVE: 'Active', SUSPENDED: 'Suspendue', ARCHIVED: 'Archivée' }

type Metrics = { missions: number; drivers: number; trucks: number; trailers: number; invoices: number }
type Organization = { id: string; name: string; slug: string; status: string; enabledModules: string[]; displayName: string | null; logoUrl: string | null; accentColor: string | null; faviconUrl: string | null; applicationTitle: string | null; createdAt: string; updatedAt: string; memberCount: number; primaryAdmin: { firstName: string; lastName: string; username: string } | null; metrics: Metrics }
type Domain = { id: string; hostname: string; pathPrefix: string; isPrimary: boolean; isActive: boolean }
type Member = { id: string; role: string; createdAt: string; user: { id: string; firstName: string; lastName: string; username: string; email: string | null; isActive: boolean; createdAt: string } }
type Audit = { id: string; action: string; metadata: unknown; createdAt: string; actor: { firstName: string; lastName: string; username: string } }
type BillingConfig = { legalName: string; legalAddress: string | null; vatNumber: string | null; iban: string | null; bic: string | null; bankName: string | null; beneficiary: string | null; invoicePrefix: string | null; paymentTermsDays: number | null; billingEmail: string | null }
type Integration = { id: string; type: 'MAIL_INTAKE' | 'SL_AUTOMOTIVE'; enabled: boolean; configJson: Record<string, unknown>; secretConfigured: boolean }
type Detail = Organization & { users: Member[]; platformAuditLogs: Audit[]; domains: Domain[]; billingConfig: BillingConfig | null; integrations: Integration[] }
type Dashboard = { organizations: Organization[]; summary: { organizations: number; active: number; suspended: number; archived: number; users: number; missions: number; drivers: number; vehicles: number }; platformRole: 'SUPER_ADMIN' | 'PLATFORM_SUPPORT' }
type AvailableUser = { id: string; firstName: string; lastName: string; username: string; email: string | null; isActive: boolean }

const emptyOrganization = { name: '', slug: '', status: 'ACTIVE', enabledModules: [...modules] as string[], adminFirstName: '', adminLastName: '', adminUsername: '', adminEmail: '', adminPassword: '' }

export default function PlatformAdminPage({ accessDenied = false }: { accessDenied?: boolean }) {
  const [data, setData] = useState<Dashboard | null>(null)
  const [detail, setDetail] = useState<Detail | null>(null)
  const [availableUsers, setAvailableUsers] = useState<AvailableUser[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [notice, setNotice] = useState('')
  const [createOpen, setCreateOpen] = useState(false)
  const [form, setForm] = useState(emptyOrganization)
  const canWrite = data?.platformRole === 'SUPER_ADMIN'

  async function loadDashboard() {
    setLoading(true); setError('')
    try {
      const response = await fetch('/api/platform/organizations')
      const body = await response.json()
      if (!response.ok) throw new Error(body.error || 'Chargement impossible')
      setData(body)
    } catch (cause) { setError(cause instanceof Error ? cause.message : 'Chargement impossible') }
    finally { setLoading(false) }
  }

  async function openOrganization(id: string) {
    setError('')
    const response = await fetch(`/api/platform/organizations/${id}`)
    const body = await response.json()
    if (!response.ok) return setError(body.error || 'Chargement impossible')
    setDetail({ ...body.organization, memberCount: body.organization.users.length, primaryAdmin: null })
    setAvailableUsers(body.availableUsers)
  }

  useEffect(() => { void loadDashboard() }, [])
  const kpis = useMemo(() => data ? [['Organisations', data.summary.organizations], ['Actives', data.summary.active], ['Suspendues', data.summary.suspended], ['Utilisateurs', data.summary.users], ['Missions', data.summary.missions], ['Chauffeurs', data.summary.drivers], ['Véhicules', data.summary.vehicles]] : [], [data])

  async function request(url: string, init: RequestInit, success: string) {
    setError(''); setNotice('')
    const response = await fetch(url, { ...init, headers: { 'Content-Type': 'application/json', ...(init.headers || {}) } })
    const body = await response.json()
    if (!response.ok) throw new Error(body.error || 'Opération impossible')
    setNotice(success)
    await loadDashboard()
    if (detail) await openOrganization(detail.id)
    return body
  }

  async function createOrganization(event: FormEvent) {
    event.preventDefault()
    try {
      const admin = form.adminUsername ? { firstName: form.adminFirstName, lastName: form.adminLastName, username: form.adminUsername, email: form.adminEmail, password: form.adminPassword } : null
      await request('/api/platform/organizations', { method: 'POST', body: JSON.stringify({ name: form.name, slug: form.slug, status: form.status, enabledModules: form.enabledModules, admin }) }, 'Organisation créée.')
      setCreateOpen(false); setForm(emptyOrganization)
    } catch (cause) { setError(cause instanceof Error ? cause.message : 'Création impossible') }
  }

  async function updateDetail(patch: Record<string, unknown>, success: string) {
    if (!detail) return
    try { await request(`/api/platform/organizations/${detail.id}`, { method: 'PATCH', body: JSON.stringify(patch) }, success) }
    catch (cause) { setError(cause instanceof Error ? cause.message : 'Modification impossible') }
  }

  if (accessDenied) return <main className="flex min-h-screen items-center justify-center bg-[#eef0ea] p-5 text-[#171914]"><section className="w-full max-w-lg rounded-[32px] bg-[#11130f] p-8 text-white shadow-2xl"><p className="text-[10px] font-black uppercase tracking-[.24em] text-[#C8FF00]">GERARD · Plateforme</p><h1 className="mt-3 text-3xl font-semibold">Accès interdit</h1><p className="mt-3 text-sm text-white/60">Cette zone est réservée aux rôles plateforme autorisés.</p><a href="/dispatch" className="mt-6 inline-flex rounded-2xl bg-white px-5 py-3 text-sm font-bold text-black">Retour au dispatch</a></section></main>

  return <main className="min-h-screen bg-[#eef0ea] px-4 py-5 text-[#171914] sm:px-7 lg:px-10">
    <div className="mx-auto max-w-[1580px]">
      <header className="rounded-[32px] bg-[#11130f] px-5 py-6 text-white shadow-[0_24px_70px_rgba(15,17,13,.22)] sm:px-8 sm:py-8">
        <div className="flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><div><p className="text-[10px] font-black uppercase tracking-[.28em] text-[#C8FF00]">GERARD · Plateforme</p><h1 className="mt-2 text-4xl font-semibold tracking-tight sm:text-5xl">Centre d’administration</h1><p className="mt-2 max-w-2xl text-sm text-white/60">Organisations, accès et modules depuis une couche plateforme séparée.</p></div><div className="flex flex-wrap gap-2">{canWrite && <button onClick={() => setCreateOpen(true)} className="h-11 rounded-2xl bg-[#C8FF00] px-5 text-sm font-black text-black">＋ Organisation</button>}<a href="/dispatch" className="inline-flex h-11 items-center rounded-2xl bg-white/10 px-5 text-sm font-bold text-white">Dispatch</a><LogoutButton tone="dark" /></div></div>
        {data?.platformRole === 'PLATFORM_SUPPORT' && <p className="mt-5 rounded-2xl border border-white/10 bg-white/5 px-4 py-3 text-xs text-white/70">Mode support : consultation uniquement.</p>}
      </header>
      {notice && <Banner tone="success">{notice}</Banner>}{error && <Banner tone="error">{error}</Banner>}
      <section className="mt-5 grid grid-cols-2 gap-3 md:grid-cols-4 xl:grid-cols-7">{kpis.map(([label, value]) => <article key={String(label)} className="rounded-[24px] border border-black/[.06] bg-white p-4 shadow-sm"><p className="text-3xl font-semibold">{value}</p><p className="mt-4 text-[9px] font-black uppercase tracking-[.14em] text-[#747a6f]">{label}</p></article>)}</section>
      <section className="mt-5 overflow-hidden rounded-[30px] border border-black/[.06] bg-white shadow-sm"><div className="border-b border-black/[.06] px-5 py-5 sm:px-7"><h2 className="text-xl font-semibold">Organisations</h2><p className="mt-1 text-sm text-[#747a6f]">Ouvrez une organisation pour gérer ses membres, modules et statut.</p></div>{loading ? <div className="flex min-h-[260px] items-center justify-center"><span className="h-9 w-9 animate-spin rounded-full border-4 border-black/10 border-t-[#8eb800]" /></div> : data?.organizations.length ? <div className="divide-y divide-black/[.06]">{data.organizations.map((organization) => <button key={organization.id} onClick={() => void openOrganization(organization.id)} className="grid w-full gap-4 px-5 py-5 text-left transition hover:bg-[#f7f8f4] sm:grid-cols-[1.5fr_.7fr_.7fr_.7fr_auto] sm:items-center sm:px-7"><div><p className="font-semibold">{organization.name}</p><p className="text-xs text-[#7a8075]">/{organization.slug} · {organization.primaryAdmin ? `${organization.primaryAdmin.firstName} ${organization.primaryAdmin.lastName}` : 'Aucun admin'}</p></div><Status value={organization.status} /><Metric label="Membres" value={organization.memberCount} /><Metric label="Missions" value={organization.metrics.missions} /><span className="text-sm font-bold text-[#668500]">Ouvrir →</span></button>)}</div> : <div className="py-16 text-center text-sm text-[#747a6f]">Aucune organisation.</div>}</section>
    </div>
    {createOpen && <Modal title="Nouvelle organisation" close={() => setCreateOpen(false)}><form onSubmit={createOrganization} className="space-y-5"><div className="grid gap-4 sm:grid-cols-2"><Field label="Nom" value={form.name} set={(name) => setForm({ ...form, name })} required /><Field label="Slug" value={form.slug} set={(slug) => setForm({ ...form, slug })} placeholder="généré si vide" /><Select label="Statut" value={form.status} set={(status) => setForm({ ...form, status })} options={Object.entries(statusLabels)} /></div><ModuleGrid selected={form.enabledModules} set={(enabledModules) => setForm({ ...form, enabledModules })} disabled={false} /><div className="rounded-3xl bg-[#f4f6f0] p-4"><h3 className="font-semibold">ORG_ADMIN initial <span className="font-normal text-[#7a8075]">· optionnel</span></h3><div className="mt-4 grid gap-3 sm:grid-cols-2"><Field label="Prénom" value={form.adminFirstName} set={(adminFirstName) => setForm({ ...form, adminFirstName })} /><Field label="Nom" value={form.adminLastName} set={(adminLastName) => setForm({ ...form, adminLastName })} /><Field label="Username" value={form.adminUsername} set={(adminUsername) => setForm({ ...form, adminUsername })} /><Field label="Email" value={form.adminEmail} set={(adminEmail) => setForm({ ...form, adminEmail })} /><Field label="Mot de passe temporaire" type="password" value={form.adminPassword} set={(adminPassword) => setForm({ ...form, adminPassword })} /></div></div><Submit label="Créer l’organisation" /></form></Modal>}
    {detail && <OrganizationDrawer detail={detail} availableUsers={availableUsers} canWrite={canWrite} close={() => setDetail(null)} update={updateDetail} request={request} />}
  </main>
}

function OrganizationDrawer({ detail, availableUsers, canWrite, close, update, request }: { detail: Detail; availableUsers: AvailableUser[]; canWrite: boolean; close: () => void; update: (patch: Record<string, unknown>, success: string) => Promise<void>; request: (url: string, init: RequestInit, success: string) => Promise<unknown> }) {
  const [tab, setTab] = useState<'general' | 'appearance' | 'business' | 'integrations' | 'domains' | 'members' | 'modules' | 'metrics' | 'audit'>('general')
  const [general, setGeneral] = useState({ name: detail.name, slug: detail.slug, status: detail.status })
  const [member, setMember] = useState({ existingUserId: '', firstName: '', lastName: '', username: '', email: '', password: '', role: 'VIEWER' })
  useEffect(() => setGeneral({ name: detail.name, slug: detail.slug, status: detail.status }), [detail])
  async function addMember(event: FormEvent) { event.preventDefault(); await request(`/api/platform/organizations/${detail.id}/members`, { method: 'POST', body: JSON.stringify(member) }, 'Membre ajouté.'); setMember({ existingUserId: '', firstName: '', lastName: '', username: '', email: '', password: '', role: 'VIEWER' }) }
  return <div className="fixed inset-0 z-50 flex justify-end bg-black/35 backdrop-blur-sm" onMouseDown={(event) => event.target === event.currentTarget && close()}><aside className="h-full w-full max-w-[760px] overflow-y-auto bg-[#f2f4ef] p-4 shadow-2xl sm:p-7"><div className="sticky top-0 z-10 rounded-[28px] bg-[#11130f] p-5 text-white"><div className="flex items-start justify-between gap-4"><div><p className="text-[9px] font-black uppercase tracking-[.25em] text-[#C8FF00]">Organisation</p><h2 className="mt-1 text-3xl font-semibold">{detail.name}</h2><p className="text-sm text-white/50">/{detail.slug}</p></div><button onClick={close} className="h-10 w-10 rounded-full bg-white/10 text-xl">×</button></div><div className="mt-5 flex gap-2 overflow-x-auto">{(['general', 'appearance', 'business', 'integrations', 'domains', 'members', 'modules', 'metrics', 'audit'] as const).map((item) => <button key={item} onClick={() => setTab(item)} className={`whitespace-nowrap rounded-full px-4 py-2 text-xs font-bold ${tab === item ? 'bg-[#C8FF00] text-black' : 'bg-white/10'}`}>{({ general: 'Général', appearance: 'Apparence', business: 'Configuration métier', integrations: 'Intégrations', domains: 'Domaines', members: 'Membres', modules: 'Modules', metrics: 'Métriques', audit: 'Audit' })[item]}</button>)}</div></div>
    <div className="mt-4 rounded-[28px] bg-white p-5 sm:p-6">
      {tab === 'general' && <div className="space-y-4"><div className="grid gap-4 sm:grid-cols-2"><Field label="Nom" value={general.name} set={(name) => setGeneral({ ...general, name })} disabled={!canWrite} /><Field label="Slug" value={general.slug} set={(slug) => setGeneral({ ...general, slug })} disabled={!canWrite} /><Select label="Statut" value={general.status} set={(status) => setGeneral({ ...general, status })} options={Object.entries(statusLabels)} disabled={!canWrite} /></div><p className="text-xs text-[#747a6f]">Créée le {formatDate(detail.createdAt)} · mise à jour le {formatDate(detail.updatedAt)}</p>{canWrite && <button onClick={() => void update(general, 'Organisation mise à jour.')} className="rounded-2xl bg-black px-5 py-3 text-sm font-bold text-white">Enregistrer</button>} {detail.status !== 'ACTIVE' && <p className="rounded-2xl bg-amber-50 p-4 text-sm text-amber-900">Les données sont conservées. Les accès métier de cette organisation sont bloqués.</p>}</div>}
      {tab === 'appearance' && <AppearancePanel detail={detail} canWrite={canWrite} update={update} />}
      {tab === 'business' && <BillingPanel detail={detail} canWrite={canWrite} request={request} />}
      {tab === 'integrations' && <IntegrationsPanel detail={detail} canWrite={canWrite} request={request} />}
      {tab === 'domains' && <DomainsPanel detail={detail} canWrite={canWrite} request={request} />}
      {tab === 'members' && <div><div className="space-y-3">{detail.users.map((membership) => <div key={membership.id} className="flex flex-col gap-3 rounded-2xl bg-[#f6f7f3] p-4 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><p className="font-semibold">{membership.user.firstName} {membership.user.lastName}</p><p className="truncate text-xs text-[#747a6f]">{membership.user.email || membership.user.username} · ajouté le {formatDate(membership.createdAt)}</p></div><select disabled={!canWrite} value={membership.role} onChange={(event) => void request(`/api/platform/organizations/${detail.id}/members/${membership.id}`, { method: 'PATCH', body: JSON.stringify({ role: event.target.value }) }, 'Rôle modifié.')} className="h-10 rounded-xl border border-black/10 bg-white px-3 text-xs font-bold">{roles.map((role) => <option key={role} value={role}>{roleLabels[role]}</option>)}</select>{canWrite && <button onClick={() => confirm('Retirer ce membre de l’organisation ?') && void request(`/api/platform/organizations/${detail.id}/members/${membership.id}`, { method: 'DELETE' }, 'Membre retiré.')} className="text-xs font-bold text-red-700">Retirer</button>}</div>)}</div>{canWrite && <form onSubmit={addMember} className="mt-6 rounded-3xl border border-black/[.06] p-4"><h3 className="font-semibold">Ajouter un membre</h3>{availableUsers.length > 0 && <Select label="Utilisateur existant" value={member.existingUserId} set={(existingUserId) => setMember({ ...member, existingUserId })} options={[['', 'Créer un nouvel utilisateur'], ...availableUsers.map((user) => [user.id, `${user.firstName} ${user.lastName} · ${user.username}`])]} />} {!member.existingUserId && <div className="mt-3 grid gap-3 sm:grid-cols-2"><Field label="Prénom" value={member.firstName} set={(firstName) => setMember({ ...member, firstName })} /><Field label="Nom" value={member.lastName} set={(lastName) => setMember({ ...member, lastName })} /><Field label="Username" value={member.username} set={(username) => setMember({ ...member, username })} /><Field label="Email" value={member.email} set={(email) => setMember({ ...member, email })} /><Field type="password" label="Mot de passe temporaire" value={member.password} set={(password) => setMember({ ...member, password })} /></div>}<div className="mt-3"><Select label="Rôle" value={member.role} set={(role) => setMember({ ...member, role })} options={roles.map((role) => [role, roleLabels[role]])} /></div><div className="mt-4"><Submit label="Ajouter" /></div></form>}</div>}
      {tab === 'modules' && <div><ModuleGrid selected={detail.enabledModules} set={(enabledModules) => void update({ enabledModules }, 'Modules mis à jour.')} disabled={!canWrite} /><p className="mt-4 text-xs text-[#747a6f]">Les modules désactivés sont refusés côté serveur, même si une URL API est appelée directement.</p></div>}
      {tab === 'metrics' && <div className="grid grid-cols-2 gap-3 sm:grid-cols-5">{Object.entries(detail.metrics).map(([label, value]) => <article key={label} className="rounded-2xl bg-[#f4f6f0] p-4"><p className="text-2xl font-semibold">{value}</p><p className="mt-2 text-[9px] font-black uppercase tracking-wider text-[#747a6f]">{({ missions: 'Missions', drivers: 'Chauffeurs', trucks: 'Camions', trailers: 'Remorques', invoices: 'Factures' } as Record<string, string>)[label]}</p></article>)}</div>}
      {tab === 'audit' && <div className="space-y-3">{detail.platformAuditLogs.length ? detail.platformAuditLogs.map((audit) => <div key={audit.id} className="rounded-2xl bg-[#f4f6f0] p-4"><div className="flex justify-between gap-3"><p className="text-sm font-bold">{auditLabel(audit.action)}</p><time className="text-[10px] text-[#747a6f]">{formatDate(audit.createdAt)}</time></div><p className="mt-1 text-xs text-[#747a6f]">{audit.actor.firstName} {audit.actor.lastName || audit.actor.username}</p></div>) : <p className="py-10 text-center text-sm text-[#747a6f]">Aucune action administrative enregistrée.</p>}</div>}
    </div></aside></div>
}

function BillingPanel({ detail, canWrite, request }: { detail: Detail; canWrite: boolean; request: (url: string, init: RequestInit, success: string) => Promise<unknown> }) {
  const initial = detail.billingConfig || { legalName: '', legalAddress: '', vatNumber: '', iban: '', bic: '', bankName: '', beneficiary: '', invoicePrefix: '', paymentTermsDays: 30, billingEmail: '' }
  const [value, setValue] = useState<Record<string, string>>({ ...Object.fromEntries(Object.entries(initial).map(([key, item]) => [key, item === null ? '' : String(item)])) })
  useEffect(() => setValue({ ...Object.fromEntries(Object.entries(detail.billingConfig || initial).map(([key, item]) => [key, item === null ? '' : String(item)])) }), [detail])
  const fields = [['legalName', 'Raison sociale'], ['legalAddress', 'Adresse légale'], ['vatNumber', 'TVA'], ['iban', 'IBAN'], ['bic', 'BIC'], ['bankName', 'Banque'], ['beneficiary', 'Bénéficiaire'], ['invoicePrefix', 'Préfixe facture'], ['paymentTermsDays', 'Délai de paiement (jours)'], ['billingEmail', 'Email facturation']]
  return <div><h3 className="text-xl font-semibold">Configuration métier</h3><p className="mt-1 text-xs text-[#747a6f]">Identité légale distincte du branding. Les factures existantes conservent leur snapshot.</p><div className="mt-5 grid gap-4 sm:grid-cols-2">{fields.map(([key, label]) => <Field key={key} label={label} value={value[key] || ''} set={(next) => setValue({ ...value, [key]: next })} disabled={!canWrite} />)}</div>{canWrite && <button onClick={() => void request(`/api/platform/organizations/${detail.id}/billing`, { method: 'PUT', body: JSON.stringify(value) }, 'Configuration métier enregistrée.')} className="mt-5 rounded-2xl bg-black px-5 py-3 text-sm font-bold text-white">Enregistrer</button>}</div>
}

function IntegrationsPanel({ detail, canWrite, request }: { detail: Detail; canWrite: boolean; request: (url: string, init: RequestInit, success: string) => Promise<unknown> }) {
  const [drafts, setDrafts] = useState<Record<string, { enabled: boolean; secretRef: string; configJson: string }>>({})
  const getDraft = (type: 'MAIL_INTAKE' | 'SL_AUTOMOTIVE') => drafts[type] || (() => { const current = detail.integrations.find((item) => item.type === type); return { enabled: current?.enabled || false, secretRef: '', configJson: JSON.stringify(current?.configJson || (type === 'MAIL_INTAKE' ? { mailboxAddress: '', host: '', port: 993, secure: true, folder: 'INBOX', provider: 'imap' } : { apiBaseUrl: '', sourceCompany: '', sourceSystem: '', providerName: 'SL Automotive', webhookEnabled: false }), null, 2) } })()
  return <div><h3 className="text-xl font-semibold">Intégrations</h3><p className="mt-1 text-xs text-[#747a6f]">Les secrets ne sont jamais affichés. Une référence vide conserve le secret existant.</p><div className="mt-5 space-y-4">{(['MAIL_INTAKE', 'SL_AUTOMOTIVE'] as const).map((type) => { const current = detail.integrations.find((item) => item.type === type); const draft = getDraft(type); return <article key={type} className="rounded-3xl bg-[#f4f6f0] p-4"><div className="flex items-center justify-between"><h4 className="font-black">{type}</h4><span className="text-xs font-bold">Secret : {current?.secretConfigured ? 'Configuré' : 'Non configuré'}</span></div><label className="mt-4 flex items-center gap-2 text-xs font-bold"><input type="checkbox" disabled={!canWrite} checked={draft.enabled} onChange={(e) => setDrafts({ ...drafts, [type]: { ...draft, enabled: e.target.checked } })} /> Activée</label><textarea disabled={!canWrite} value={draft.configJson} onChange={(e) => setDrafts({ ...drafts, [type]: { ...draft, configJson: e.target.value } })} className="mt-3 min-h-40 w-full rounded-2xl border border-black/10 bg-white p-3 font-mono text-xs" /><Field label="Nouvelle référence de secret (optionnel)" value={draft.secretRef} set={(secretRef) => setDrafts({ ...drafts, [type]: { ...draft, secretRef } })} disabled={!canWrite} />{canWrite && <button onClick={() => { try { const configJson = JSON.parse(draft.configJson); void request(`/api/platform/organizations/${detail.id}/integrations`, { method: 'PUT', body: JSON.stringify({ type, enabled: draft.enabled, configJson, ...(draft.secretRef ? { secretRef: draft.secretRef } : {}) }) }, `${type} enregistrée.`) } catch { alert('JSON invalide') } }} className="mt-3 rounded-2xl bg-black px-4 py-2 text-xs font-bold text-white">Enregistrer</button>}</article> })}</div></div>
}

function AppearancePanel({ detail, canWrite, update }: { detail: Detail; canWrite: boolean; update: (patch: Record<string, unknown>, success: string) => Promise<void> }) {
  const [value, setValue] = useState({ displayName: detail.displayName || '', logoUrl: detail.logoUrl || '', accentColor: detail.accentColor || '#C8FF00', faviconUrl: detail.faviconUrl || '', applicationTitle: detail.applicationTitle || '' })
  useEffect(() => setValue({ displayName: detail.displayName || '', logoUrl: detail.logoUrl || '', accentColor: detail.accentColor || '#C8FF00', faviconUrl: detail.faviconUrl || '', applicationTitle: detail.applicationTitle || '' }), [detail])
  return <div className="space-y-5"><div className="grid gap-4 sm:grid-cols-2"><Field label="Nom affiché" value={value.displayName} set={(displayName) => setValue({ ...value, displayName })} disabled={!canWrite} placeholder="Gerard" /><Field label="Titre application" value={value.applicationTitle} set={(applicationTitle) => setValue({ ...value, applicationTitle })} disabled={!canWrite} placeholder="Gerard Dispatch" /><Field label="URL du logo" value={value.logoUrl} set={(logoUrl) => setValue({ ...value, logoUrl })} disabled={!canWrite} placeholder="https://… ou /asset.png" /><Field label="URL du favicon" value={value.faviconUrl} set={(faviconUrl) => setValue({ ...value, faviconUrl })} disabled={!canWrite} placeholder="https://… ou /favicon.ico" /><label className="block text-[10px] font-black uppercase tracking-[.14em] text-[#747a6f]">Couleur d’accent<div className="mt-2 flex gap-2"><input type="color" value={/^#[0-9A-Fa-f]{6}$/.test(value.accentColor) ? value.accentColor : '#C8FF00'} disabled={!canWrite} onChange={(event) => setValue({ ...value, accentColor: event.target.value.toUpperCase() })} className="h-11 w-14 rounded-xl border border-black/10 bg-white p-1" /><input value={value.accentColor} disabled={!canWrite} onChange={(event) => setValue({ ...value, accentColor: event.target.value })} className="field" /></div></label></div><div className="rounded-3xl bg-[#f4f6f0] p-5"><p className="text-[10px] font-black uppercase tracking-widest text-[#747a6f]">Aperçu</p><div className="mt-4 flex items-center gap-4"><div className="flex h-16 min-w-32 items-center justify-center rounded-2xl bg-white p-3">{value.logoUrl ? <img src={value.logoUrl} alt="Aperçu" className="max-h-10 max-w-28 object-contain" /> : <span className="font-black">Gerard</span>}</div><div><p className="text-xl font-semibold">{value.displayName || 'Gerard'}</p><span style={{ backgroundColor: value.accentColor }} className="mt-2 inline-block rounded-xl px-4 py-2 text-xs font-black text-black">Action principale</span></div></div></div>{canWrite && <button onClick={() => void update(value, 'Apparence mise à jour.')} className="rounded-2xl bg-black px-5 py-3 text-sm font-bold text-white">Enregistrer l’apparence</button>}<p className="text-xs text-[#747a6f]">Les champs vides utilisent le branding Gerard centralisé.</p></div>
}

function DomainsPanel({ detail, canWrite, request }: { detail: Detail; canWrite: boolean; request: (url: string, init: RequestInit, success: string) => Promise<unknown> }) {
  const [value, setValue] = useState({ hostname: '', pathPrefix: '', isPrimary: false })
  return <div className="space-y-4"><div className="space-y-3">{detail.domains.map((domain) => <article key={domain.id} className="rounded-2xl bg-[#f4f6f0] p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-semibold">{domain.hostname}{domain.pathPrefix}</p><p className="text-xs text-[#747a6f]">{domain.isPrimary ? 'Principal · ' : ''}{domain.isActive ? 'Actif' : 'Inactif'}</p></div>{canWrite && <div className="flex gap-2"><button onClick={() => void request(`/api/platform/organizations/${detail.id}/domains/${domain.id}`, { method: 'PATCH', body: JSON.stringify({ isPrimary: true, isActive: true }) }, 'Domaine principal défini.')} className="text-xs font-bold">Principal</button><button onClick={() => void request(`/api/platform/organizations/${detail.id}/domains/${domain.id}`, { method: 'PATCH', body: JSON.stringify({ isActive: !domain.isActive }) }, 'Domaine mis à jour.')} className="text-xs font-bold">{domain.isActive ? 'Désactiver' : 'Activer'}</button><button onClick={() => confirm('Supprimer ce mapping de domaine ?') && void request(`/api/platform/organizations/${detail.id}/domains/${domain.id}`, { method: 'DELETE' }, 'Domaine supprimé.')} className="text-xs font-bold text-red-700">Supprimer</button></div>}</div></article>)}</div>{canWrite && <form onSubmit={(event) => { event.preventDefault(); void request(`/api/platform/organizations/${detail.id}/domains`, { method: 'POST', body: JSON.stringify(value) }, 'Domaine ajouté.').then(() => setValue({ hostname: '', pathPrefix: '', isPrimary: false })) }} className="rounded-3xl border border-black/[.06] p-4"><h3 className="font-semibold">Ajouter un domaine</h3><div className="mt-3 grid gap-3 sm:grid-cols-2"><Field label="Hostname" value={value.hostname} set={(hostname) => setValue({ ...value, hostname })} placeholder="dispatch.client.com" required /><Field label="Préfixe optionnel" value={value.pathPrefix} set={(pathPrefix) => setValue({ ...value, pathPrefix })} placeholder="/dispatch" /></div><label className="mt-3 flex items-center gap-2 text-xs font-bold"><input type="checkbox" checked={value.isPrimary} onChange={(event) => setValue({ ...value, isPrimary: event.target.checked })} /> Domaine principal</label><div className="mt-4"><Submit label="Ajouter le domaine" /></div></form>}<p className="text-xs text-[#747a6f]">Aucune modification DNS n’est effectuée par Gerard.</p></div>
}

function ModuleGrid({ selected, set, disabled }: { selected: readonly string[]; set: (value: string[]) => void; disabled: boolean }) { return <div><p className="mb-3 text-[10px] font-black uppercase tracking-[.16em] text-[#747a6f]">Modules activés</p><div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{modules.map((module) => { const active = selected.includes(module); return <button type="button" disabled={disabled} key={module} onClick={() => set(active ? selected.filter((item) => item !== module) : [...selected, module])} className={`rounded-2xl p-3 text-left text-xs font-bold transition ${active ? 'bg-black text-white' : 'bg-[#eef0ea] text-[#747a6f]'} disabled:cursor-default`}><span className={`mr-2 inline-block h-2 w-2 rounded-full ${active ? 'bg-[#C8FF00]' : 'bg-black/15'}`} />{moduleLabels[module]}</button> })}</div></div> }
function Field({ label, value, set, type = 'text', required = false, placeholder, disabled = false }: { label: string; value: string; set: (value: string) => void; type?: string; required?: boolean; placeholder?: string; disabled?: boolean }) { return <label className="block text-[10px] font-black uppercase tracking-[.14em] text-[#747a6f]">{label}<input disabled={disabled} required={required} type={type} value={value} placeholder={placeholder} onChange={(event) => set(event.target.value)} className="mt-2 h-11 w-full rounded-2xl border border-black/10 bg-white px-4 text-sm font-medium normal-case tracking-normal outline-none focus:border-[#8eb800] disabled:bg-black/[.03]" /></label> }
function Select({ label, value, set, options, disabled = false }: { label: string; value: string; set: (value: string) => void; options: string[][]; disabled?: boolean }) { return <label className="block text-[10px] font-black uppercase tracking-[.14em] text-[#747a6f]">{label}<select disabled={disabled} value={value} onChange={(event) => set(event.target.value)} className="mt-2 h-11 w-full rounded-2xl border border-black/10 bg-white px-4 text-sm font-medium normal-case tracking-normal">{options.map(([value, optionLabel]) => <option key={value || 'empty'} value={value}>{optionLabel}</option>)}</select></label> }
function Status({ value }: { value: string }) { const color = value === 'ACTIVE' ? 'bg-lime-100 text-lime-900' : value === 'SUSPENDED' ? 'bg-amber-100 text-amber-900' : 'bg-black/10 text-black/60'; return <span className={`w-fit rounded-full px-3 py-1 text-[10px] font-black uppercase tracking-wider ${color}`}>{statusLabels[value]}</span> }
function Metric({ label, value }: { label: string; value: number }) { return <div><p className="text-lg font-semibold">{value}</p><p className="text-[9px] font-black uppercase tracking-wider text-[#747a6f]">{label}</p></div> }
function Submit({ label }: { label: string }) { return <button className="h-11 rounded-2xl bg-[#C8FF00] px-5 text-sm font-black text-black">{label}</button> }
function Banner({ tone, children }: { tone: 'success' | 'error'; children: ReactNode }) { return <div className={`mt-4 rounded-2xl px-4 py-3 text-sm font-semibold ${tone === 'success' ? 'bg-lime-100 text-lime-950' : 'bg-red-100 text-red-900'}`}>{children}</div> }
function Modal({ title, close, children }: { title: string; close: () => void; children: ReactNode }) { return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4 backdrop-blur-sm" onMouseDown={(event) => event.target === event.currentTarget && close()}><section className="max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-[30px] bg-white p-5 shadow-2xl sm:p-7"><div className="mb-6 flex items-center justify-between"><h2 className="text-2xl font-semibold">{title}</h2><button onClick={close} className="h-10 w-10 rounded-full bg-black/5 text-xl">×</button></div>{children}</section></div> }
function formatDate(value: string) { return new Intl.DateTimeFormat('fr-LU', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) }
function auditLabel(action: string) { return ({ ORGANIZATION_CREATED: 'Organisation créée', ORGANIZATION_UPDATED: 'Informations modifiées', ORGANIZATION_STATUS_CHANGED: 'Statut modifié', MEMBER_ADDED: 'Membre ajouté', MEMBER_REMOVED: 'Membre retiré', MEMBER_ROLE_CHANGED: 'Rôle modifié', MODULES_CHANGED: 'Modules modifiés', BRANDING_CHANGED: 'Apparence modifiée', DOMAIN_CREATED: 'Domaine ajouté', DOMAIN_UPDATED: 'Domaine modifié', DOMAIN_DELETED: 'Domaine supprimé' } as Record<string, string>)[action] || action }

export const getServerSideProps: GetServerSideProps = async ({ req, res }) => {
  const user = await getPlatformUser(req)
  if (!user) {
    res.statusCode = 403
    return { props: { accessDenied: true } }
  }
  return { props: { accessDenied: false } }
}
